### ISSUE TITLE
an unbounded loop on array can lead to DoS

### ISSUE THREAD

**Issue by rajatbeladiya** [LodestarFinance/lodestar-protocol#13]
## Affected Contracts
Comptroller.sol

## Severity
Medium

## Description

CToken[] public allMarkets; in contract Comptroller.sol, there is an array where there are pushes new market using `_addMarketInternal`. No upper bound, no pop.
As this array can grow quite large, the transaction’s gas cost could exceed the block gas limit and make it impossible to call this function at all here:

https://github.com/LodestarFinance/lodestar-protocol/blob/cfca1ae275d023a02198798bbcb24b2a1f646776/contracts/Comptroller.sol#L1036-L1041

`_supportMarket` is calling internally `_addMarketInternal`, so it will not add the market because of gas limit DoS.

## Recommendation

Consider introducing a reasonable upper limit based on block gas limits and adding a method to remove elements in the array.

**Comment by rotcivegaf** [comment]
Don't specified **Attack scenario**

**Comment by rajatbeladiya** [comment]
@rotcivegaf it's essential to understand that not every issue in a smart contract necessarily has an exploitable attack scenario.
In this particular case, the bug I submitted causes the smart contract's functionality to cease working as intended, which is a significant problem on its own.

let the committee decide.

**Comment by 0xAppo** [comment]
While it is true that there is no upper bound on the size of the array, in practice the array will never grow large enough to exceed the block gas limit. As such, this is seen as a non-issue and not planned at this time. Additionally, it is by design that markets can not be removed from the markets array after they've been listed. This is to prevent anyone from having the ability to de-list markets.
